/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lom;

import java.text.SimpleDateFormat;
import java.lang.System;
import java.util.Date;
import java.util.TimeZone;
import java.util.Locale;
import java.util.Arrays;

public class App {

    public static void main(String[] args) {
        try{
          throw new Exception("Exception message");
        }catch(Exception e){
          String out = e.getStackTrace().toString();
          System.out.println(out);
          System.out.println(e);
        }
        Parent p = new Parent();
        p.setFirst("sato");
        Child c = new Child();
        c.setFirst("sato");
        Parent c1 = (Parent) c;
        // System.out.println(c.equals(p));
        // System.out.println(p.equals(c));
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ", Locale.ENGLISH);
        Date d = new Date(233345223232L);
        System.out.println(d);
        System.out.println(sdf.format(d));
        System.out.println("=============================");

    }

}
